version: 1
bug:
  - '/bug/i'
  - '/error/i'
  - '/not working/i'
documentation:
  - '/documentation/i'
  - '/docs/i'
  - '/readme/i'
enhancement:
  - '/enhancement/i'
  - '/feature/i'
  - '/add/i'
  - '/implement/i'