critical:
  - '(critical|urgent)'

important:
  - '(important|high)'

enhancement:
  - '(feature|new|implement|improve|improvement)'

bug:
  - '(bug|error|not working)'

documentation:
  - '(documentation|docs|readme)'