name: "Auto Label Issues"

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues
        uses: github/issue-labeler@v3.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labels.yml
          enable-versioned-regex: 0
          sync-labels: true