name: "Auto Label Issues"

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label issues
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labels.yml
          sync-labels: true